### ISSUE TITLE
`npm` module has not been updated

### ISSUE THREAD

**Issue by gnerkus** [pdyck/hearthstone-db#14]
[The missing comma fix](https://github.com/pdyck/hearthstone-db/pull/13) has not yet been added to the npm module. As a consequence, requiring `hearthstone-db` results in an error:

> wtog: wtog.cards
    ^^^^
SyntaxError: Unexpected identifier
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at repl:1:11
    at REPLServer.defaultEval (repl.js:252:27)
    at bound (domain.js:287:14)

**Comment by pdyck** [comment]
fixed
